spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionStosk
    username:
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database:
      hibernate.dll-auto: update
      generate-dll: true
      show-sql: true
