spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestionStock
    username: postgres
    password: Lam62122phil
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
      show-sql: true
